version: '3.2'

networks:
  pharmacin_docker_network: 
    external: true

services:
  pharmacin_api:
    restart: always
    build:
      context: .
      dockerfile: dockerfile
      target: dependencies
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=[port]
      - HOST=0.0.0.0
      - NODE_ENV=[development/production]
      - APP_KEY=3sHBE1aL9HdpxfGdDO7K5X9sIoKNR5Zx
      - DRIVE_DISK=local
      - DB_CONNECTION=mysql
      - MYSQL_HOST=[host_db]
      - MYSQL_PORT=[port_db]
      - MYSQL_DB_NAME=[name_db]
      - MYSQL_USER=[user_db]
      - MYSQL_PASSWORD=[pass_db]
    volumes:
      - [path docker cth:/home/project/data-docker]:/usr/src/app
    command: dumb-init node ace serve --watch --node-args="--inspect=0.0.0.0"
    networks:
      - pharmacin_docker_network
